// GENERATED by scripts/gen-icon.mjs from electron/wordmark.js — do not edit.
// The pixel rows of the Gnosis mark, so the browser UI draws the same artwork as
// the Windows icon and the tray. Regenerate with: npm run gen:icon
export const MARK_ROWS: readonly string[] = [
  ".###.",
  "#...#",
  "#....",
  "#.##.",
  "#...#",
  "#...#",
  ".###."
];
export const WORDMARK_ROWS: readonly string[] = [
  ".###..#...#..###...####.#####..####",
  "#...#.##..#.#...#.#.......#...#....",
  "#.....##..#.#...#.#.......#...#....",
  "#.##..#.#.#.#...#..###....#....###.",
  "#...#.#..##.#...#.....#...#.......#",
  "#...#.#..##.#...#.....#...#.......#",
  ".###..#...#..###..####..#####.####."
];
